### ISSUE TITLE
оффтоп

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [ivagorRetrocomp/DeZX#1]
а когда же будут сорцы, всяких там, msx эмуляторов? :)
милярды спектрумистов ждут портирования msx эмулятора на спецтрум!

**Comment by ivagorRetrocomp** [comment]
Думаю Alone Coder быстрее напишет свой вариант, он в этом деле достиг больших высот

**Comment by NEO-SPECTRUMAN** [comment]
:rofl:
если напишот он
оно будет работать только на НедоОС
будет с нечитаемым и с пинка компилируемым сорцом

**Comment by NEO-SPECTRUMAN** [comment]
а так такой эмулятор хотел делоть лично мну
а алона своих эмуляторов хватает

**Comment by ivagorRetrocomp** [comment]
Пока выкладывать исходники imsx не планирую

**Comment by NEO-SPECTRUMAN** [comment]
> Пока выкладывать исходники imsx не планирую

значит твои поделки отдизасмим 
делов то
